name: Publish Docker image

on:
  # workflow_run:
  #   workflows: ["Tag and Release"]
  #   types:
  #     - completed
  release:
    types: [published]

env:
  GM_KEY: ${{ secrets.GM_KEY }}

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          # password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: uofgiii/companion

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            GM_KEY="${{ env.GM_KEY }}"
            USER_ID=1000
            GROUP_ID=1000

  # build:
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    # runs-on: ubuntu-latest
    # env:
    #   GM_KEY: ${{ secrets.GM_KEY }}
    # steps:
    # - uses: actions/checkout@v3
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag uofg/companion:$(date +%s) --build-arg GM_KEY="$GM_KEY"
