name: Tag and release

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_release_rules: |
            "fix:patch,hotfix:patch,patch:patch,feature:minor,change:minor,minor:minor,breaking:major,major:major"
    outputs:
      new_tag: ${{ steps.tag_version.outputs.new_tag }}
      changelog: ${{ steps.tag_version.outputs.changelog }}
      release_type: ${{ steps.tag_version.outputs.release_type }}

  write-version:
    needs: build
    runs-on: ubuntu-latest
    name: Write version to file
    steps:
      - uses: actions/checkout@v2
      - name: Update version
        uses: sebastian-muthwill/write-version-to-file@master
        with:
          filename: '.version'
      - name: Commit change
        uses: stefanzweifel/git-auto-commit-action@v4

  release:
    needs: [build, write-version]
    if: ${{ contains(fromJSON('["minor", "major"]'), needs.build.outputs.release_type) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ needs.build.outputs.new_tag }}
          name: Release ${{ needs.build.outputs.new_tag }}
          body: ${{ needs.build.outputs.changelog }}
          draft: true
