name: Release

on:
  push:
    branches: [ "master" ]
  # pull_request:
  #   types: [ labeled ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    # if: ${{ github.event.label.name == 'patch' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dry_run:
